/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileDisplayer: typeof import("./src/components/FileDisplayer.vue")["default"]
    FolderExplorer: typeof import('./src/components/FolderExplorer.vue')['default']
    FolderSelector: typeof import('./src/components/FolderSelector.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    SourceDisplayer: typeof import("./src/components/SourceDisplayer.vue")["default"]
    TargetDisplayer: typeof import("./src/components/TargetDisplayer.vue")["default"]
  }
}
