// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileInfo = {
	name: string;
	path: string;
	extension: string | null;
	mime_type: string;
	size: bigint;
	created_at: bigint | null;
	modified_at: bigint | null;
	is_dir: boolean;
	is_file: boolean;
	is_symlink: boolean;
};
